articles/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from articles.views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView
from articles.apps import ArticlesConfig

app_name = ArticlesConfig.name


class ArticleEditView:
    pass


urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('view/<int:pk>', ArticleDetailView.as_view(), name='view'),
    path('edit/<int:pk>', ArticleUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls", namespace='catalog')),
    path('articles/', include("articles.urls", namespace='articles')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('reset-password/', reset_password, name='reset_password' )


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug')
    body = models.CharField(max_length=100, verbose_name='Содержание')
    preview = models.ImageField(upload_to='media/', null=True, blank=True, verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(default=True)
    count_review = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ['title', 'is_published', 'count_review']

articles/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from articles.models import Article


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'body',)
    success_url = reverse_lazy('articles:article_list')

    def form_valid(self, form):
        if form.is_valid():
            article = form.save()
            article.slug = slugify(article.title)
            article.save()
        return super().form_valid(form)


class ArticleListView(ListView):
    model = Article

    def get_queryset(self, *args, **kwargs):
        self.queryset = super().get_queryset(*args, **kwargs)
        self.queryset = self.queryset.filter(is_published=True)
        return self.queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_review += 1
        self.object.save()
        return self.object


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'body',)

    def form_valid(self, form):
        if form.is_valid():
            article = form.save()
            article.slug = slugify(article.title)
            article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articles:view', args=[self.kwargs.get('pk')])


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:article_list')

articles/templates/articles/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h6>Вы действительно хотите удалить статью {{ object.title }}</h6>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'articles:article_list' %}" class="btn btn-warning">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-md-4">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                Статья {{ object.title }}
            </h3>
        </div>

        <div class="card-body">
            <p class="card-text">
                {{ object.body }}
            </p>
        </div>
        <div class="card-footer">
            Просмотры {{ object.count_review }}
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Создать</button>
                    {% endif %}
                    <button type="button" class="btn btn-sm btn-outline-secondary">Редактировать</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'articles:create' %}">Создать статью</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{ object.title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'articles:view' object.pk %}">Просмотреть</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'articles:edit' object.pk %}">Редактировать</a>
                        <a type="button" class="btn btn-sm danger"
                           href="{% url 'articles:delete' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}