config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls", namespace='catalog')),
    path('articles/', include("articles.urls", namespace='articles')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('reset-password/', reset_password, name='reset_password' )


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='Token', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
        template_name = 'users/register.html'

users/views.py
import secrets
import string
import random

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView


from users.forms import UserRegisterForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        host = self.request.get_host()
        user.token = token
        user.save()
        url = f'http://{host}/users/email-confirm/{token}'
        send_to = form.cleaned_data['email']
        send_mail('Верификация почты',
                  f'Подтвердите свою электронную почту {url}',
                  None,
                  [send_to],
                  fail_silently=False)
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits
        password = ''.join(random.choice(characters) for i in range(8))
        user.password = make_password(password)
        user.save()
        send_mail('Сброс пароля',
                  f'Ваш новый пароль {password}',
                  None,
                  [user.email],
                  fail_silently=False)
        return redirect(reverse('users:login'))
    return render(request, 'users/reset_password.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row justify-content-left" method="post">
    <div class="col-md-6">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header">
                <h4 class="card-title">
                    Вход
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-success">Войти</button>
            <a class="btn btn-outline-primary" href="{% url 'users:reset_password' %}">Восстановить пароль</a>
        </div>
    </div>
</form>
{% endblock %}>

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}>
<form class="row justify-content-left" method="post">
    <div class="col-md-6">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header">
                <h4 class="card-title">
                    Регистрация пользователя
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-success">Регистрация</button>
        </div>
    </div>
</form>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/base.html' %}
{% block content %}
<form class="row justify-content-left" method="post">
    <div class="col-md-6">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header">
                <h4 class="card-title">
                    Восстановление пароля
                </h4>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="email" name="email" class="form-control" id="email" placeholder="Ваша почта" required>
            </div>
            <button type="submit" class="btn btn-success">Восстановить пароль</button>
        </div>
    </div>
</form>
{% endblock %}>