catalog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from catalog.views import *
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category', CategoryListView.as_view(), name='category'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete')


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("catalog.urls", namespace='catalog')),
    path('articles/', include("articles.urls", namespace='articles')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('reset-password/', reset_password, name='reset_password' )


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
import psycopg2
from config.settings import DATABASES
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='Категория')
    description = models.CharField(max_length=200, verbose_name='Описание')

    @classmethod
    def truncate_table(cls):
        conn = psycopg2.connect(database=DATABASES['default']['NAME'],
                                host=DATABASES['default']['HOST'],
                                user=DATABASES['default']['USER'],
                                password=DATABASES['default']['PASSWORD'])
        with conn.cursor() as cursor:
            cursor.execute(f'TRUNCATE TABLE {cls._meta.db_table} RESTART IDENTITY CASCADE')
        conn.commit()
        conn.close()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=30, verbose_name='Товар')
    description = models.CharField(max_length=200, verbose_name='Описание')
    image = models.ImageField(upload_to='media/', null=True, blank=True, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_products', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Товар опубликован')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        permissions = [
            (
                'set_published',
                'can publish product',
            ),
            (
                'change_description',
                'can change description',
            ),
            (
                'change_category',
                'can change category',
            )
        ]



class Version(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name='Продукт')
    number = models.CharField(max_length=10, verbose_name='Номер версии')
    is_current = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'Версия {self.name} {self.number}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.forms import BooleanField
from catalog.models import Product, Version


class StyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                pass #field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class DisableWidgetMixin:
    def __init__(self, *args, **kwargs):
        is_disabled = kwargs.pop('is_disabled')
        is_super = kwargs.pop('is_super')
        disabled_fields = ('description', 'category', 'is_published')
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if is_disabled and not is_super:
                if field_name not in disabled_fields:
                    field.widget.attrs['disabled'] = True


class ProductForm(DisableWidgetMixin, StyleMixin, forms.ModelForm):
    vorbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        exclude = ('user',)


    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     is_disabled = kwargs.pop('disabled')
    #     if is_disabled:

    def clean_name(self):
        cleaned_name = self.cleaned_data.get('name')
        for word in ProductForm.vorbidden_words:
            if word in cleaned_name:
                raise forms.ValidationError(f'Слово {word} нельзя употреблять в названии продукта')
        return cleaned_name

    def clean_description(self):
        cleaned_description = self.cleaned_data.get('description')
        for word in ProductForm.vorbidden_words:
            if word in cleaned_description:
                raise forms.ValidationError(f'Слово {word} нельзя употреблять в описании продукта')
        return cleaned_description


class VersionForm(StyleMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django import forms
from catalog.forms import ProductForm, VersionForm
from catalog.models import *
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, TemplateView

from catalog.services import get_cached_categories


class IndexView(TemplateView):
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()
        return context_data


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        product_list = Product.objects.all()
        context_data['product_versions'] = {}
        for product in product_list:
            if len(product.versions.filter(is_current=True)):
                version = product.versions.filter(is_current=True).last()
                context_data['product_versions'].update({product: version})
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    login_url = '/users/login/'
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        user = self.request.user
        product = form.save()
        product.user = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = '/users/login/'
    success_url = reverse_lazy('catalog:product_list')

    def get_form_kwargs(self, **kwargs):
        kwargs = super(ProductUpdateView, self).get_form_kwargs()
        kwargs.update({'is_disabled': self.request.user.has_perm('catalog.set_published'),
                       'is_super': self.request.user.is_superuser})
        return kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        counter = 0
        for form_version in formset:
            if form_version.is_valid():
                if form_version.cleaned_data.get('is_current'):
                    counter += 1
        if counter > 1:
            form.add_error(None, ValidationError('Только одна версия товара может быть активной'))
            return self.form_invalid(form)
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def form_invalid(self, form):
        context_data = self.get_context_data()
        context_data['form'] = form
        return self.render_to_response(context_data)


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    login_url = '/users/login/'
    success_url = reverse_lazy('catalog:product_list')


class CategoryListView(ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['objects'] = get_cached_categories()
        return context_data


class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {'title': 'Контакты'}

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Магазин электроники</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Меню</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        {% include 'catalog/includes/inc_menu.html' %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Поиск">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
    </div>
</nav>

<main role="main">
    <div class="jumbotron">
        <div class="container">
            <header>
                <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
                    <h1 class="display-3">Магазин электроники</h1>
                    <p class="fs-5 text-body-secondary">Вы находитесь на сайте, предназначенном для продажи товаров</p>
                </div>
            </header>
        </div>
    </div>
    <div class="container">
        <!-- Example row of columns -->
        {% block content %}

        {% endblock %}
    </div>
</main>

<footer class="container">
    <p>&copy; Company 2024</p>
</footer>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Категории товаров</h4>
            </div>
            <div class="card-body">
                <ul>
                    {% for object in objects %}
                    <li>
                        {{ object.name }}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>5406285846</td>
                        </tr>
                        <tr>
                            <td class="w-25">ОГРН</td>
                            <td>1045402490100</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Новосибирск, ул. Гоголя, 13, ТРЦ "Галерея Новосибирск" </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="{{ object.name }}" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="{{ object.phone }}" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваш вопрос или пожелание" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="col-md-4 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:category' %}">Категории товаров</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4 text-center">
        <div class="card rounded-3 shadow-sm mb-2" style="min-height: 400px">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <img src="{% add_path object.image %}" class="img-fluid" style="width: auto; max-height: 300px"
                 alt="Изображения нет">
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }}$</h2>
                <p>
                    {{ object.description | slice:100 }}
                </p>
                <button type="button" class="w-100 btn btn-lg btn-success">Купить</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="col-4">
    <div class="card rounded-3 width-50 mt-3 mb-5">
        <div class="card-body">
            <form method="post" action="">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name" class="form-label">Имя</label>
                    <input type="text" name="name" class="form-control" id="name"
                           placeholder="Ваше имя"
                           aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" name="email" class="form-control" id="email"
                           placeholder="Ваш email">
                </div>
                <button type="submit" class="btn btn-primary form-control">Отправить</button>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <h2 class="pricing-header p-3 pb-md-10 mx-auto text-center">FAQ</h2>
    </div>
    <div class="col-4">
        <p>
            <button class="btn btn-primary form-control" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseWidthExample1" aria-expanded="false"
                    aria-controls="collapseWidthExample1">
                Как купить?
            </button>
        </p>
        <div style="min-height: 120px;">
            <div class="collapse collapse-horizontal" id="collapseWidthExample1">
                <div class="card card-body form-control" style="width: 300px;">
                    Купить наш товар очень просто.
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <p>
            <button class="btn btn-primary form-control" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseWidthExample2" aria-expanded="false"
                    aria-controls="collapseWidthExample2">
                Как доставить?
            </button>
        </p>
        <div style="min-height: 120px;">
            <div class="collapse collapse-horizontal" id="collapseWidthExample2">
                <div class="card card-body form-control" style="width: 300px;">
                    Доставить можно любой логистической компанией.
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <p>
            <button class="btn btn-primary form-control" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseWidthExample3" aria-expanded="false"
                    aria-controls="collapseWidthExample3">
                Какая гарантия?
            </button>
        </p>
        <div style="min-height: 120px;">
            <div class="collapse collapse-horizontal" id="collapseWidthExample3">
                <div class="card card-body form-control" style="width: 300px;">
                    Гарантия предоставляется заводом изготовителем.
                </div>
            </div>
        </div>
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Номер</th>
        <th scope="col">Название товара</th>
        <th scope="col">Цена за штуку</th>
        <th scope="col">Количество</th>
        <th scope="col">Итоговая сумма</th>
        <th scope="col">Статус заказа</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <td>Смартфон Samsung</td>
        <td>70</td>
        <td>10</td>
        <td>700</td>
        <td>
            <div class="alert alert-primary" role="alert">
                новый
            </div>
        </td>
    </tr>
    <tr>
        <th scope="row">2</th>
        <td>Смартфон Apple</td>
        <td>100</td>
        <td>15</td>
        <td>1500</td>
        <td>
            <div class="alert alert-warning" role="alert">
                обработка
            </div>
        </td>
    </tr>
    <tr>
        <th scope="row">3</th>
        <td>Смарфон Xiaomi</td>
        <td>50</td>
        <td>20</td>
        <td>1000</td>
        <td>
            <div class="alert alert-success" role="alert">
                обработан
            </div>
        </td>
    </tr>
    </tbody>
</table>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<!--<div class="container">-->
    <div class="row justify-content-center">
        <div class="col-md-4 text-center">
            <div class="card rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ category }}</h4><br>
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <img src="{% add_path object.image %}" class="card-img-top" alt="Изображения нет">
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.price }}$</h2>
                    <p>
                        {{ object.description }}
                    </p>
                    <button type="button" class="w-100 btn btn-lg btn-success">Купить</button>
                </div>
            </div>
        </div>
    </div>
<!--</div>-->
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}>
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card rounded-3 shadow-sm pl-2">
            <form method="post">
                {% csrf_token %}
                <h6>Вы действительно хотите удалить статью {{ object.name }}</h6>
                <button type="submit" class="btn btn-danger">Подтвердить</button>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Отменить</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<!--<div class="container">-->
    <div class="row justify-content-center">
        <div class="col-md-4 text-center">
            <div class="card rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ category }}</h4><br>
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <img src="{% add_path object.image %}" class="card-img-top" alt="Изображения нет">
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ object.price }}$</h2>
                    <p>
                        {{ object.description }}
                    </p>
                    <button type="button" class="w-100 btn btn-lg btn-success">Купить</button>
                </div>
            </div>
        </div>
    </div>
<!--</div>-->
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}>
<form class="row justify-content-center" method="post">
    <div class="col-md-6">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header">
                {% if object %}
                <h4 class="card-title">
                    Изменение товара
                </h4>
                {% else %}
                <h4 class="card-title">
                    Добавление товара
                </h4>
                {% endif %}
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
            {% if object %}
            <button type="submit" class="btn btn-success">Сохранить</button>
            {% else %}
            <button type="submit" class="btn btn-success">Создать</button>
            {% endif %}
        </div>
        {% if form.non_field_errors %}
        <div class="alert alert-danger">
            <ul>
                {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Версии товара
                </h4>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="col-md-4 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create' %}">Создать продукт</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4 text-center">
        <div class="card rounded-3 shadow-sm mb-2" style="min-height: 400px">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div>
                <img src="{% add_path object.image %}" class="img-fluid" style="width: auto; max-height: 300px"
                     alt="Изображения нет">
            </div>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.price }}$</h2>
                <p>
                    {{ object.description | slice:100 }}
                </p>
                {% if object in product_versions %}
                <p>
                    {% get_value product_versions object %}
                </p>
                {% endif %}
                <button type="button" class="w-100 btn btn-lg btn-success">Купить</button>
            </div>
            <div class="card-footer">
                <div class="bnt-group">
                    <a type="button" href="{% url 'catalog:product' object.pk %}" class="btn btn-sm btn-secondary mb-1">Посмотреть</a>
                    {% if perms.catalog.set_published or user == object.user %}
                    <a type="button" href="{% url 'catalog:edit' object.pk %}" class="btn btn-sm btn-warning mb-1">Редактировать</a>
                    {% endif %}
                    {% if user == object.user %}
                    <a type="button" href="{% url 'catalog:delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}